SELECT DISTINCT CAR.CAR_ID, CAR.CAR_TYPE,
    ROUND(CAR.DAILY_FEE*30*(1- COALESCE(PLAN.DISCOUNT_RATE,0)/100), 0) AS 'FEE'
FROM (SELECT CAR_ID, CAR_TYPE, DAILY_FEE FROM CAR_RENTAL_COMPANY_CAR 
      WHERE CAR_TYPE IN('세단', 'SUV')
      ) CAR
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN PLAN
    ON CAR.CAR_TYPE = PLAN.CAR_TYPE AND PLAN.DURATION_TYPE = '30일 이상'
    WHERE CAR.DAILY_FEE*30*(1- COALESCE(PLAN.DISCOUNT_RATE,0)/100) 
        BETWEEN 500000 AND 2000000
    AND CAR.CAR_ID NOT IN (
        SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
        WHERE NOT (END_DATE < '2022-11-01' OR START_DATE >'2022-11-30')
    )
ORDER BY FEE DESC, CAR.CAR_TYPE, CAR.CAR_ID DESC;