SELECT B.FOOD_TYPE, A.REST_ID, A.REST_NAME, B.FAVORITES
FROM REST_INFO AS A
    RIGHT JOIN (SELECT FOOD_TYPE , MAX(FAVORITES) AS FAVORITES
         FROM REST_INFO 
         GROUP BY FOOD_TYPE) AS B
    ON A.FOOD_TYPE = B.FOOD_TYPE
WHERE A.FAVORITES = B.FAVORITES
ORDER BY FOOD_TYPE DESC