# SELECT YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH, I.GENDER, I.USER_ID
# FROM (SELECT USER_ID, GENDER FROM USER_INFO WHERE GENDER IS NOT NULL) AS I
#     JOIN (SELECT USER_ID, SALES_DATE
#           FROM ONLINE_SALE 
#           GROUP BY DATE_FORMAT(SALES_DATE, '%Y-%m')
#          ) AS S
#     ON I.USER_ID = S.USER_ID
# ORDER BY YEAR, MONTH, GENDER

SELECT 
    YEAR(S.SALES_DATE) AS YEAR, 
    MONTH(S.SALES_DATE) AS MONTH, 
    I.GENDER, 
    COUNT(DISTINCT S.USER_ID) AS USERS
FROM USER_INFO I
JOIN (
    SELECT USER_ID, SALES_DATE
    FROM ONLINE_SALE
    GROUP BY USER_ID, DATE_FORMAT(SALES_DATE, '%Y-%m')
) AS S
ON I.USER_ID = S.USER_ID
WHERE I.GENDER IS NOT NULL
GROUP BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE), I.GENDER
ORDER BY YEAR, MONTH, GENDER;
