WITH CTE AS (
    SELECT COUNT(*) AS COUNT_2021_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = '2021')

SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH,
    COUNT(DISTINCT USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT USER_ID)/COUNT_2021_ID, 1) AS PUCHASED_RATIO
FROM ONLINE_SALE , CTE
WHERE USER_ID IN (
    SELECT USER_ID AS COUNT_2021_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = '2021'
)
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH