SELECT F.HISTORY_ID,
    ROUND(F.FEE*(1- IFNULL(P.DISCOUNT_RATE,0)/100)) AS FEE      
FROM (SELECT H.HISTORY_ID, H.CAR_ID, C.CAR_TYPE,
      C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE)+1) AS FEE,
      DATEDIFF(H.END_DATE, H.START_DATE)+1 AS DURATION
     FROM CAR_RENTAL_COMPANY_CAR C
     JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
     ON C.CAR_ID = H.CAR_ID AND C.CAR_TYPE = '트럭'
     ) F
     LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
     ON F.CAR_TYPE = P.CAR_TYPE
     AND(
        DURATION_TYPE =
        CASE
            WHEN F.DURATION >= 90 THEN '90일 이상'
            WHEN F.DURATION >= 30 THEN '30일 이상'
            WHEN F.DURATION >= 7 THEN '7일 이상'
        END 
     )
ORDER BY FEE DESC, F.HISTORY_ID DESC