SELECT FLAVOR
FROM (
    SELECT FLAVOR, TOTAL_ORDER
    FROM FIRST_HALF 
    UNION
    SELECT FLAVOR, SUM(TOTAL_ORDER)
    FROM JULY
    GROUP BY FLAVOR
    ) F
GROUP BY FLAVOR
ORDER BY SUM(TOTAL_ORDER) DESC LIMIT 3